### ISSUE TITLE
Pages breaking up, buffer not filling

### ISSUE THREAD

**Issue by avrovulcanxh607** [peterkvt80/vbit-py#1]
Getting an output like this:

SPIRAM created
Buffer created
Fifo created
vbit.py System started
?
x 183?
x 273?
x 363?
x 453?
x 498?
?
x 183?
x 588?
x 405?
?
x 405?
?
x 363?
?
x 45?
x 405?
x 588?
x 180?
x 495?

**Comment by peterkvt80** [comment]
It was tested with a Raspberry Pi 3 B v1.2 and a class 10 SD card. There is only a single buffer so it relies on a fast system that isn't loaded by other tasks.. I'll double buffer and see if that helps slower systems.

**Comment by avrovulcanxh607** [comment]
Thanks, yes this is the older RPI B1. I tried overclocking it to 1 GHz, it helped a bit but still not working very well.

**Comment by avrovulcanxh607** [comment]
Nope, still not working on the B1

**Comment by ZXGuesser** [comment]
It could be because you're toggling GPIO pins. I seem to recall the python GPIO driver works through the linux filesystem so consumes a lot of processor time for every operation.

Edit: apparently not, perhaps I'm thinking of a different python module.

**Comment by peterkvt80** [comment]
Buffering didn't help because the Python is way too slow for an original Pi. I think that the main problem is the highly inefficient way of reversing the bits of each byte. Namely doing a bunch of operations then appending the result to an array for each of 720 bytes per field. Vectorising and using numpy would be much more efficient. We wouldn't even need to do it but vbit2 reverses the bit order which it only does because that is how raspi-teletext wants it. If we avoided doing the reverse then an un-reverse we would save a lot of cpu time.

**Comment by ZXGuesser** [comment]
We could add a command line option for vbit2 to reverse the bits before output in Packet::tx
I think any double-reversing of bits has long since been removed, the only thing that gets reversed is some data in the broadcast service data packet that is reversed from normal. That is using a 256 byte look up table.

**Comment by avrovulcanxh607** [comment]
Yes, that seems to be the problem. Removing calls to 'reverseBuffer' stops all the empty Buffer warnings, although it obviously won't work

**Comment by avrovulcanxh607** [comment]
Well, it works for a few minutes and then you get this:
Traceback (most recent call last):
  File "/home/pi/vbit-py/vbit.py", line 71, in fieldEdge
    fifo.spiram.spi.writebytes(buf.field)
AttributeError: 'list' object has no attribute 'field'

**Comment by peterkvt80** [comment]
That parameter should be buf[tail].field but I haven't committed it yet.
I'll add a command line option to vbit2 to reverse the bit order and then I
can remove it from vbit-py. I have dusted off my original  Pi and installed
the latest Raspian so I can test it tonight.

**Comment by ZXGuesser** [comment]
I'm just doing that Peter, got it 90% done, just trying to hunt down some filler packets that are escaping un-reversed!

**Comment by peterkvt80** [comment]
You guys are obviously taking over this project. Would either of you like
to be promoted to contributor so you can update it?

**Comment by avrovulcanxh607** [comment]
Yeah OK.

**Comment by ZXGuesser** [comment]
OK, try the vbit2 I just pushed, with --reverse on the command line https://github.com/peterkvt80/vbit2/commit/9e1837ac67e898502e655f511ea2043415ed994b

**Comment by avrovulcanxh607** [comment]
It's helped, but still not running perfectly. Looking like there's no choice but to use a faster Pi...

**Comment by ZXGuesser** [comment]
There has to be a way, if the original pi could do it with the old inefficient vbit it must have enough cpu time left with vbit2. Python may have a more efficient way to deal with streams like this, or maybe it's just the wrong tool for the job.

**Comment by avrovulcanxh607** [comment]
No, I'm happy to say that it's now working perfectly! (For some reason I had two running at once). Thanks!
